In [1]:
import numpy as np

In [14]:
def array_factory(mode: str, shape: list, value: float = None):

    if mode == "zeros":
        return np.full((shape[0],shape[1]), 0)
    
    if mode == "ones":
        return np.full((shape[0],shape[1]), 1)
    
    if mode == "full":
        return np.full((shape[0],shape[1]), value)
    
    if mode == "identity":
        if shape[0] != shape[1]:
            return "Error: Identity matrex must be square matrix"

        return np.eye(shape[0])
        

print(array_factory("zeros", [2,4]))
print(array_factory("ones", [2,4]))
print(array_factory("full", [2,4], 12))
print(array_factory("ones", [2,4],))
print(array_factory("identity", [2,4]))
print(array_factory("identity", [5,5]))



[[0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]]
[[12 12 12 12]
 [12 12 12 12]]
[[1 1 1 1]
 [1 1 1 1]]
Error: Identity matrex must be square matrix
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [26]:
def secure_reshape_and_stack(data1: list, data2: list, new_shape:list):

    try:
        arr1 = np.array(data1)
        arr2 = np.array(data2)

        reshaped_arr1 = arr1.reshape(new_shape[0], new_shape[1])

        combined_dataset = np.vstack((reshaped_arr1, arr2))

        return combined_dataset
    
    except ValueError as e:
        raise ValueError (f"Company-grade Error: {e}")


data_list_1 = [1, 2, 3, 4, 5, 6] 
shape_to_apply = [2, 3] 
data_list_2 = [[7, 8, 9], 
               [10, 11, 12]]

success_result = secure_reshape_and_stack(data_list_1, data_list_2, shape_to_apply)
print(success_result)
print("-" * 40)

bad_data_list = [[7, 8], 
                 [10, 11]]

try:
    error_result = secure_reshape_and_stack(data_list_1, bad_data_list, shape_to_apply)
except ValueError as error_message:
    print(error_message)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
----------------------------------------
Company-grade Error: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2
